context:
  version: "0.39.0"

package:
  name: rbspy
  version: ${{ version }}

source:
  url: https://github.com/rbspy/rbspy/archive/v${{ version }}.tar.gz
  sha256: 772476d59f047287e20c2cc362937b518664621e100fa24430c3012a148088fd

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - rbspy --help

about:
  license: MIT
  license_file:
    - License.md
    - THIRDPARTY.yml
  summary: Sampling profiler for Ruby
  homepage: https://rbspy.github.io/
  repository: https://github.com/rbspy/rbspy

extra:
  recipe-maintainers:
    - danielnachun
