context:
  version: "0.46.0"

package:
  name: rbspy
  version: ${{ version }}

source:
  url: https://github.com/rbspy/rbspy/archive/v${{ version }}.tar.gz
  sha256: 055c59b2180e7a1d192d479b9e559312fcc8100d330c9851a0b632c1f793fb4b

build:
  number: 0
  skip: ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - rbspy --help

about:
  license: MIT
  license_file:
    - License.md
    - THIRDPARTY.yml
  summary: Sampling profiler for Ruby
  homepage: https://rbspy.github.io/
  repository: https://github.com/rbspy/rbspy

extra:
  recipe-maintainers:
    - danielnachun
