context:
  version: "0.52.1"

package:
  name: rbspy
  version: ${{ version }}

source:
  url: https://github.com/rbspy/rbspy/archive/v${{ version }}.tar.gz
  sha256: e5bd0126e6585d57fcb8deee7db3b04ffbdfad36074eb1b799b48791f6219449

build:
  number: 0
  skip: ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - rbspy --help

about:
  license: MIT
  license_file:
    - License.md
    - THIRDPARTY.yml
  summary: Sampling profiler for Ruby
  homepage: https://rbspy.github.io/
  repository: https://github.com/rbspy/rbspy

extra:
  recipe-maintainers:
    - danielnachun
