context:
  version: "0.34.0"

package:
  name: rbspy
  version: ${{ version }}

source:
  url: https://github.com/rbspy/rbspy/archive/v${{ version }}.tar.gz
  sha256: dc2eceb963ef9a5687de89fef38c28ebd4dab857ed7dfc20b51602f45c6d76ea

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - rbspy --help

about:
  license: MIT
  license_file:
    - License.md
    - THIRDPARTY.yml
  summary: Sampling profiler for Ruby
  homepage: https://rbspy.github.io/
  repository: https://github.com/rbspy/rbspy

extra:
  recipe-maintainers:
    - danielnachun
