context:
  version: "0.48.0"

package:
  name: rbspy
  version: ${{ version }}

source:
  url: https://github.com/rbspy/rbspy/archive/v${{ version }}.tar.gz
  sha256: bef36cf5ea8573f671e375ec0043db108012a16de5f68eddc9463a0058b0642b

build:
  number: 0
  skip: ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - rbspy --help

about:
  license: MIT
  license_file:
    - License.md
    - THIRDPARTY.yml
  summary: Sampling profiler for Ruby
  homepage: https://rbspy.github.io/
  repository: https://github.com/rbspy/rbspy

extra:
  recipe-maintainers:
    - danielnachun
